// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MarketData.proto

package com.solutionarchitects;

public final class MarketData {
  private MarketData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LevelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.solutionarchitects.Level)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double price = 1;</code>
     */
    double getPrice();

    /**
     * <code>optional int32 askSize = 2;</code>
     */
    int getAskSize();

    /**
     * <code>optional int32 bidSize = 3;</code>
     */
    int getBidSize();
  }
  /**
   * Protobuf type {@code com.solutionarchitects.Level}
   */
  public  static final class Level extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.solutionarchitects.Level)
      LevelOrBuilder {
    // Use Level.newBuilder() to construct.
    private Level(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Level() {
      price_ = 0D;
      askSize_ = 0;
      bidSize_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Level(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              price_ = input.readDouble();
              break;
            }
            case 16: {

              askSize_ = input.readInt32();
              break;
            }
            case 24: {

              bidSize_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.solutionarchitects.MarketData.internal_static_com_solutionarchitects_Level_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.solutionarchitects.MarketData.internal_static_com_solutionarchitects_Level_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.solutionarchitects.MarketData.Level.class, com.solutionarchitects.MarketData.Level.Builder.class);
    }

    public static final int PRICE_FIELD_NUMBER = 1;
    private double price_;
    /**
     * <code>optional double price = 1;</code>
     */
    public double getPrice() {
      return price_;
    }

    public static final int ASKSIZE_FIELD_NUMBER = 2;
    private int askSize_;
    /**
     * <code>optional int32 askSize = 2;</code>
     */
    public int getAskSize() {
      return askSize_;
    }

    public static final int BIDSIZE_FIELD_NUMBER = 3;
    private int bidSize_;
    /**
     * <code>optional int32 bidSize = 3;</code>
     */
    public int getBidSize() {
      return bidSize_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (price_ != 0D) {
        output.writeDouble(1, price_);
      }
      if (askSize_ != 0) {
        output.writeInt32(2, askSize_);
      }
      if (bidSize_ != 0) {
        output.writeInt32(3, bidSize_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (price_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, price_);
      }
      if (askSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, askSize_);
      }
      if (bidSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, bidSize_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.solutionarchitects.MarketData.Level)) {
        return super.equals(obj);
      }
      com.solutionarchitects.MarketData.Level other = (com.solutionarchitects.MarketData.Level) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getPrice())
          == java.lang.Double.doubleToLongBits(
              other.getPrice()));
      result = result && (getAskSize()
          == other.getAskSize());
      result = result && (getBidSize()
          == other.getBidSize());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      hash = (37 * hash) + ASKSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getAskSize();
      hash = (37 * hash) + BIDSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getBidSize();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.solutionarchitects.MarketData.Level parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.solutionarchitects.MarketData.Level parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.solutionarchitects.MarketData.Level parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.solutionarchitects.MarketData.Level parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.solutionarchitects.MarketData.Level parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.solutionarchitects.MarketData.Level parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.solutionarchitects.MarketData.Level parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.solutionarchitects.MarketData.Level parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.solutionarchitects.MarketData.Level parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.solutionarchitects.MarketData.Level parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.solutionarchitects.MarketData.Level prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.solutionarchitects.Level}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.solutionarchitects.Level)
        com.solutionarchitects.MarketData.LevelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.solutionarchitects.MarketData.internal_static_com_solutionarchitects_Level_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.solutionarchitects.MarketData.internal_static_com_solutionarchitects_Level_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.solutionarchitects.MarketData.Level.class, com.solutionarchitects.MarketData.Level.Builder.class);
      }

      // Construct using com.solutionarchitects.MarketData.Level.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        price_ = 0D;

        askSize_ = 0;

        bidSize_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.solutionarchitects.MarketData.internal_static_com_solutionarchitects_Level_descriptor;
      }

      public com.solutionarchitects.MarketData.Level getDefaultInstanceForType() {
        return com.solutionarchitects.MarketData.Level.getDefaultInstance();
      }

      public com.solutionarchitects.MarketData.Level build() {
        com.solutionarchitects.MarketData.Level result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.solutionarchitects.MarketData.Level buildPartial() {
        com.solutionarchitects.MarketData.Level result = new com.solutionarchitects.MarketData.Level(this);
        result.price_ = price_;
        result.askSize_ = askSize_;
        result.bidSize_ = bidSize_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.solutionarchitects.MarketData.Level) {
          return mergeFrom((com.solutionarchitects.MarketData.Level)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.solutionarchitects.MarketData.Level other) {
        if (other == com.solutionarchitects.MarketData.Level.getDefaultInstance()) return this;
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        if (other.getAskSize() != 0) {
          setAskSize(other.getAskSize());
        }
        if (other.getBidSize() != 0) {
          setBidSize(other.getBidSize());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.solutionarchitects.MarketData.Level parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.solutionarchitects.MarketData.Level) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double price_ ;
      /**
       * <code>optional double price = 1;</code>
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <code>optional double price = 1;</code>
       */
      public Builder setPrice(double value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double price = 1;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0D;
        onChanged();
        return this;
      }

      private int askSize_ ;
      /**
       * <code>optional int32 askSize = 2;</code>
       */
      public int getAskSize() {
        return askSize_;
      }
      /**
       * <code>optional int32 askSize = 2;</code>
       */
      public Builder setAskSize(int value) {
        
        askSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 askSize = 2;</code>
       */
      public Builder clearAskSize() {
        
        askSize_ = 0;
        onChanged();
        return this;
      }

      private int bidSize_ ;
      /**
       * <code>optional int32 bidSize = 3;</code>
       */
      public int getBidSize() {
        return bidSize_;
      }
      /**
       * <code>optional int32 bidSize = 3;</code>
       */
      public Builder setBidSize(int value) {
        
        bidSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bidSize = 3;</code>
       */
      public Builder clearBidSize() {
        
        bidSize_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.solutionarchitects.Level)
    }

    // @@protoc_insertion_point(class_scope:com.solutionarchitects.Level)
    private static final com.solutionarchitects.MarketData.Level DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.solutionarchitects.MarketData.Level();
    }

    public static com.solutionarchitects.MarketData.Level getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Level>
        PARSER = new com.google.protobuf.AbstractParser<Level>() {
      public Level parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Level(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Level> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Level> getParserForType() {
      return PARSER;
    }

    public com.solutionarchitects.MarketData.Level getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MarketDataMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.solutionarchitects.MarketDataMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
     */
    java.util.List<com.solutionarchitects.MarketData.Level> 
        getPriceLevelsList();
    /**
     * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
     */
    com.solutionarchitects.MarketData.Level getPriceLevels(int index);
    /**
     * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
     */
    int getPriceLevelsCount();
    /**
     * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
     */
    java.util.List<? extends com.solutionarchitects.MarketData.LevelOrBuilder> 
        getPriceLevelsOrBuilderList();
    /**
     * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
     */
    com.solutionarchitects.MarketData.LevelOrBuilder getPriceLevelsOrBuilder(
        int index);

    /**
     * <code>optional int32 ask0 = 2;</code>
     */
    int getAsk0();

    /**
     * <code>optional int32 ask1 = 3;</code>
     */
    int getAsk1();

    /**
     * <code>optional int32 ask2 = 4;</code>
     */
    int getAsk2();

    /**
     * <code>optional int32 ask3 = 5;</code>
     */
    int getAsk3();

    /**
     * <code>optional int32 ask4 = 6;</code>
     */
    int getAsk4();

    /**
     * <code>optional int32 bid0 = 7;</code>
     */
    int getBid0();

    /**
     * <code>optional int32 bid1 = 8;</code>
     */
    int getBid1();

    /**
     * <code>optional int32 bid2 = 9;</code>
     */
    int getBid2();

    /**
     * <code>optional int32 bid3 = 11;</code>
     */
    int getBid3();

    /**
     * <code>optional int32 bid4 = 12;</code>
     */
    int getBid4();

    /**
     * <code>optional int32 askSize0 = 13;</code>
     */
    int getAskSize0();

    /**
     * <code>optional int32 askSize1 = 14;</code>
     */
    int getAskSize1();

    /**
     * <code>optional int32 askSize2 = 15;</code>
     */
    int getAskSize2();

    /**
     * <code>optional int32 askSize3 = 16;</code>
     */
    int getAskSize3();

    /**
     * <code>optional int32 askSize4 = 17;</code>
     */
    int getAskSize4();

    /**
     * <code>optional int32 bidSize0 = 18;</code>
     */
    int getBidSize0();

    /**
     * <code>optional int32 bidSize1 = 19;</code>
     */
    int getBidSize1();

    /**
     * <code>optional int32 bidSize2 = 20;</code>
     */
    int getBidSize2();

    /**
     * <code>optional int32 bidSize3 = 21;</code>
     */
    int getBidSize3();

    /**
     * <code>optional int32 bidSize4 = 22;</code>
     */
    int getBidSize4();

    /**
     * <code>optional string recordId = 23;</code>
     */
    java.lang.String getRecordId();
    /**
     * <code>optional string recordId = 23;</code>
     */
    com.google.protobuf.ByteString
        getRecordIdBytes();

    /**
     * <code>optional string exchange = 24;</code>
     */
    java.lang.String getExchange();
    /**
     * <code>optional string exchange = 24;</code>
     */
    com.google.protobuf.ByteString
        getExchangeBytes();
  }
  /**
   * Protobuf type {@code com.solutionarchitects.MarketDataMessage}
   */
  public  static final class MarketDataMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.solutionarchitects.MarketDataMessage)
      MarketDataMessageOrBuilder {
    // Use MarketDataMessage.newBuilder() to construct.
    private MarketDataMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MarketDataMessage() {
      priceLevels_ = java.util.Collections.emptyList();
      ask0_ = 0;
      ask1_ = 0;
      ask2_ = 0;
      ask3_ = 0;
      ask4_ = 0;
      bid0_ = 0;
      bid1_ = 0;
      bid2_ = 0;
      bid3_ = 0;
      bid4_ = 0;
      askSize0_ = 0;
      askSize1_ = 0;
      askSize2_ = 0;
      askSize3_ = 0;
      askSize4_ = 0;
      bidSize0_ = 0;
      bidSize1_ = 0;
      bidSize2_ = 0;
      bidSize3_ = 0;
      bidSize4_ = 0;
      recordId_ = "";
      exchange_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MarketDataMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                priceLevels_ = new java.util.ArrayList<com.solutionarchitects.MarketData.Level>();
                mutable_bitField0_ |= 0x00000001;
              }
              priceLevels_.add(
                  input.readMessage(com.solutionarchitects.MarketData.Level.parser(), extensionRegistry));
              break;
            }
            case 16: {

              ask0_ = input.readInt32();
              break;
            }
            case 24: {

              ask1_ = input.readInt32();
              break;
            }
            case 32: {

              ask2_ = input.readInt32();
              break;
            }
            case 40: {

              ask3_ = input.readInt32();
              break;
            }
            case 48: {

              ask4_ = input.readInt32();
              break;
            }
            case 56: {

              bid0_ = input.readInt32();
              break;
            }
            case 64: {

              bid1_ = input.readInt32();
              break;
            }
            case 72: {

              bid2_ = input.readInt32();
              break;
            }
            case 88: {

              bid3_ = input.readInt32();
              break;
            }
            case 96: {

              bid4_ = input.readInt32();
              break;
            }
            case 104: {

              askSize0_ = input.readInt32();
              break;
            }
            case 112: {

              askSize1_ = input.readInt32();
              break;
            }
            case 120: {

              askSize2_ = input.readInt32();
              break;
            }
            case 128: {

              askSize3_ = input.readInt32();
              break;
            }
            case 136: {

              askSize4_ = input.readInt32();
              break;
            }
            case 144: {

              bidSize0_ = input.readInt32();
              break;
            }
            case 152: {

              bidSize1_ = input.readInt32();
              break;
            }
            case 160: {

              bidSize2_ = input.readInt32();
              break;
            }
            case 168: {

              bidSize3_ = input.readInt32();
              break;
            }
            case 176: {

              bidSize4_ = input.readInt32();
              break;
            }
            case 186: {
              java.lang.String s = input.readStringRequireUtf8();

              recordId_ = s;
              break;
            }
            case 194: {
              java.lang.String s = input.readStringRequireUtf8();

              exchange_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          priceLevels_ = java.util.Collections.unmodifiableList(priceLevels_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.solutionarchitects.MarketData.internal_static_com_solutionarchitects_MarketDataMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.solutionarchitects.MarketData.internal_static_com_solutionarchitects_MarketDataMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.solutionarchitects.MarketData.MarketDataMessage.class, com.solutionarchitects.MarketData.MarketDataMessage.Builder.class);
    }

    private int bitField0_;
    public static final int PRICELEVELS_FIELD_NUMBER = 1;
    private java.util.List<com.solutionarchitects.MarketData.Level> priceLevels_;
    /**
     * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
     */
    public java.util.List<com.solutionarchitects.MarketData.Level> getPriceLevelsList() {
      return priceLevels_;
    }
    /**
     * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
     */
    public java.util.List<? extends com.solutionarchitects.MarketData.LevelOrBuilder> 
        getPriceLevelsOrBuilderList() {
      return priceLevels_;
    }
    /**
     * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
     */
    public int getPriceLevelsCount() {
      return priceLevels_.size();
    }
    /**
     * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
     */
    public com.solutionarchitects.MarketData.Level getPriceLevels(int index) {
      return priceLevels_.get(index);
    }
    /**
     * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
     */
    public com.solutionarchitects.MarketData.LevelOrBuilder getPriceLevelsOrBuilder(
        int index) {
      return priceLevels_.get(index);
    }

    public static final int ASK0_FIELD_NUMBER = 2;
    private int ask0_;
    /**
     * <code>optional int32 ask0 = 2;</code>
     */
    public int getAsk0() {
      return ask0_;
    }

    public static final int ASK1_FIELD_NUMBER = 3;
    private int ask1_;
    /**
     * <code>optional int32 ask1 = 3;</code>
     */
    public int getAsk1() {
      return ask1_;
    }

    public static final int ASK2_FIELD_NUMBER = 4;
    private int ask2_;
    /**
     * <code>optional int32 ask2 = 4;</code>
     */
    public int getAsk2() {
      return ask2_;
    }

    public static final int ASK3_FIELD_NUMBER = 5;
    private int ask3_;
    /**
     * <code>optional int32 ask3 = 5;</code>
     */
    public int getAsk3() {
      return ask3_;
    }

    public static final int ASK4_FIELD_NUMBER = 6;
    private int ask4_;
    /**
     * <code>optional int32 ask4 = 6;</code>
     */
    public int getAsk4() {
      return ask4_;
    }

    public static final int BID0_FIELD_NUMBER = 7;
    private int bid0_;
    /**
     * <code>optional int32 bid0 = 7;</code>
     */
    public int getBid0() {
      return bid0_;
    }

    public static final int BID1_FIELD_NUMBER = 8;
    private int bid1_;
    /**
     * <code>optional int32 bid1 = 8;</code>
     */
    public int getBid1() {
      return bid1_;
    }

    public static final int BID2_FIELD_NUMBER = 9;
    private int bid2_;
    /**
     * <code>optional int32 bid2 = 9;</code>
     */
    public int getBid2() {
      return bid2_;
    }

    public static final int BID3_FIELD_NUMBER = 11;
    private int bid3_;
    /**
     * <code>optional int32 bid3 = 11;</code>
     */
    public int getBid3() {
      return bid3_;
    }

    public static final int BID4_FIELD_NUMBER = 12;
    private int bid4_;
    /**
     * <code>optional int32 bid4 = 12;</code>
     */
    public int getBid4() {
      return bid4_;
    }

    public static final int ASKSIZE0_FIELD_NUMBER = 13;
    private int askSize0_;
    /**
     * <code>optional int32 askSize0 = 13;</code>
     */
    public int getAskSize0() {
      return askSize0_;
    }

    public static final int ASKSIZE1_FIELD_NUMBER = 14;
    private int askSize1_;
    /**
     * <code>optional int32 askSize1 = 14;</code>
     */
    public int getAskSize1() {
      return askSize1_;
    }

    public static final int ASKSIZE2_FIELD_NUMBER = 15;
    private int askSize2_;
    /**
     * <code>optional int32 askSize2 = 15;</code>
     */
    public int getAskSize2() {
      return askSize2_;
    }

    public static final int ASKSIZE3_FIELD_NUMBER = 16;
    private int askSize3_;
    /**
     * <code>optional int32 askSize3 = 16;</code>
     */
    public int getAskSize3() {
      return askSize3_;
    }

    public static final int ASKSIZE4_FIELD_NUMBER = 17;
    private int askSize4_;
    /**
     * <code>optional int32 askSize4 = 17;</code>
     */
    public int getAskSize4() {
      return askSize4_;
    }

    public static final int BIDSIZE0_FIELD_NUMBER = 18;
    private int bidSize0_;
    /**
     * <code>optional int32 bidSize0 = 18;</code>
     */
    public int getBidSize0() {
      return bidSize0_;
    }

    public static final int BIDSIZE1_FIELD_NUMBER = 19;
    private int bidSize1_;
    /**
     * <code>optional int32 bidSize1 = 19;</code>
     */
    public int getBidSize1() {
      return bidSize1_;
    }

    public static final int BIDSIZE2_FIELD_NUMBER = 20;
    private int bidSize2_;
    /**
     * <code>optional int32 bidSize2 = 20;</code>
     */
    public int getBidSize2() {
      return bidSize2_;
    }

    public static final int BIDSIZE3_FIELD_NUMBER = 21;
    private int bidSize3_;
    /**
     * <code>optional int32 bidSize3 = 21;</code>
     */
    public int getBidSize3() {
      return bidSize3_;
    }

    public static final int BIDSIZE4_FIELD_NUMBER = 22;
    private int bidSize4_;
    /**
     * <code>optional int32 bidSize4 = 22;</code>
     */
    public int getBidSize4() {
      return bidSize4_;
    }

    public static final int RECORDID_FIELD_NUMBER = 23;
    private volatile java.lang.Object recordId_;
    /**
     * <code>optional string recordId = 23;</code>
     */
    public java.lang.String getRecordId() {
      java.lang.Object ref = recordId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string recordId = 23;</code>
     */
    public com.google.protobuf.ByteString
        getRecordIdBytes() {
      java.lang.Object ref = recordId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCHANGE_FIELD_NUMBER = 24;
    private volatile java.lang.Object exchange_;
    /**
     * <code>optional string exchange = 24;</code>
     */
    public java.lang.String getExchange() {
      java.lang.Object ref = exchange_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exchange_ = s;
        return s;
      }
    }
    /**
     * <code>optional string exchange = 24;</code>
     */
    public com.google.protobuf.ByteString
        getExchangeBytes() {
      java.lang.Object ref = exchange_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exchange_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < priceLevels_.size(); i++) {
        output.writeMessage(1, priceLevels_.get(i));
      }
      if (ask0_ != 0) {
        output.writeInt32(2, ask0_);
      }
      if (ask1_ != 0) {
        output.writeInt32(3, ask1_);
      }
      if (ask2_ != 0) {
        output.writeInt32(4, ask2_);
      }
      if (ask3_ != 0) {
        output.writeInt32(5, ask3_);
      }
      if (ask4_ != 0) {
        output.writeInt32(6, ask4_);
      }
      if (bid0_ != 0) {
        output.writeInt32(7, bid0_);
      }
      if (bid1_ != 0) {
        output.writeInt32(8, bid1_);
      }
      if (bid2_ != 0) {
        output.writeInt32(9, bid2_);
      }
      if (bid3_ != 0) {
        output.writeInt32(11, bid3_);
      }
      if (bid4_ != 0) {
        output.writeInt32(12, bid4_);
      }
      if (askSize0_ != 0) {
        output.writeInt32(13, askSize0_);
      }
      if (askSize1_ != 0) {
        output.writeInt32(14, askSize1_);
      }
      if (askSize2_ != 0) {
        output.writeInt32(15, askSize2_);
      }
      if (askSize3_ != 0) {
        output.writeInt32(16, askSize3_);
      }
      if (askSize4_ != 0) {
        output.writeInt32(17, askSize4_);
      }
      if (bidSize0_ != 0) {
        output.writeInt32(18, bidSize0_);
      }
      if (bidSize1_ != 0) {
        output.writeInt32(19, bidSize1_);
      }
      if (bidSize2_ != 0) {
        output.writeInt32(20, bidSize2_);
      }
      if (bidSize3_ != 0) {
        output.writeInt32(21, bidSize3_);
      }
      if (bidSize4_ != 0) {
        output.writeInt32(22, bidSize4_);
      }
      if (!getRecordIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 23, recordId_);
      }
      if (!getExchangeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 24, exchange_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < priceLevels_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, priceLevels_.get(i));
      }
      if (ask0_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ask0_);
      }
      if (ask1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, ask1_);
      }
      if (ask2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, ask2_);
      }
      if (ask3_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, ask3_);
      }
      if (ask4_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, ask4_);
      }
      if (bid0_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, bid0_);
      }
      if (bid1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, bid1_);
      }
      if (bid2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, bid2_);
      }
      if (bid3_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, bid3_);
      }
      if (bid4_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, bid4_);
      }
      if (askSize0_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, askSize0_);
      }
      if (askSize1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, askSize1_);
      }
      if (askSize2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, askSize2_);
      }
      if (askSize3_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, askSize3_);
      }
      if (askSize4_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, askSize4_);
      }
      if (bidSize0_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(18, bidSize0_);
      }
      if (bidSize1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(19, bidSize1_);
      }
      if (bidSize2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, bidSize2_);
      }
      if (bidSize3_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(21, bidSize3_);
      }
      if (bidSize4_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(22, bidSize4_);
      }
      if (!getRecordIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(23, recordId_);
      }
      if (!getExchangeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(24, exchange_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.solutionarchitects.MarketData.MarketDataMessage)) {
        return super.equals(obj);
      }
      com.solutionarchitects.MarketData.MarketDataMessage other = (com.solutionarchitects.MarketData.MarketDataMessage) obj;

      boolean result = true;
      result = result && getPriceLevelsList()
          .equals(other.getPriceLevelsList());
      result = result && (getAsk0()
          == other.getAsk0());
      result = result && (getAsk1()
          == other.getAsk1());
      result = result && (getAsk2()
          == other.getAsk2());
      result = result && (getAsk3()
          == other.getAsk3());
      result = result && (getAsk4()
          == other.getAsk4());
      result = result && (getBid0()
          == other.getBid0());
      result = result && (getBid1()
          == other.getBid1());
      result = result && (getBid2()
          == other.getBid2());
      result = result && (getBid3()
          == other.getBid3());
      result = result && (getBid4()
          == other.getBid4());
      result = result && (getAskSize0()
          == other.getAskSize0());
      result = result && (getAskSize1()
          == other.getAskSize1());
      result = result && (getAskSize2()
          == other.getAskSize2());
      result = result && (getAskSize3()
          == other.getAskSize3());
      result = result && (getAskSize4()
          == other.getAskSize4());
      result = result && (getBidSize0()
          == other.getBidSize0());
      result = result && (getBidSize1()
          == other.getBidSize1());
      result = result && (getBidSize2()
          == other.getBidSize2());
      result = result && (getBidSize3()
          == other.getBidSize3());
      result = result && (getBidSize4()
          == other.getBidSize4());
      result = result && getRecordId()
          .equals(other.getRecordId());
      result = result && getExchange()
          .equals(other.getExchange());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getPriceLevelsCount() > 0) {
        hash = (37 * hash) + PRICELEVELS_FIELD_NUMBER;
        hash = (53 * hash) + getPriceLevelsList().hashCode();
      }
      hash = (37 * hash) + ASK0_FIELD_NUMBER;
      hash = (53 * hash) + getAsk0();
      hash = (37 * hash) + ASK1_FIELD_NUMBER;
      hash = (53 * hash) + getAsk1();
      hash = (37 * hash) + ASK2_FIELD_NUMBER;
      hash = (53 * hash) + getAsk2();
      hash = (37 * hash) + ASK3_FIELD_NUMBER;
      hash = (53 * hash) + getAsk3();
      hash = (37 * hash) + ASK4_FIELD_NUMBER;
      hash = (53 * hash) + getAsk4();
      hash = (37 * hash) + BID0_FIELD_NUMBER;
      hash = (53 * hash) + getBid0();
      hash = (37 * hash) + BID1_FIELD_NUMBER;
      hash = (53 * hash) + getBid1();
      hash = (37 * hash) + BID2_FIELD_NUMBER;
      hash = (53 * hash) + getBid2();
      hash = (37 * hash) + BID3_FIELD_NUMBER;
      hash = (53 * hash) + getBid3();
      hash = (37 * hash) + BID4_FIELD_NUMBER;
      hash = (53 * hash) + getBid4();
      hash = (37 * hash) + ASKSIZE0_FIELD_NUMBER;
      hash = (53 * hash) + getAskSize0();
      hash = (37 * hash) + ASKSIZE1_FIELD_NUMBER;
      hash = (53 * hash) + getAskSize1();
      hash = (37 * hash) + ASKSIZE2_FIELD_NUMBER;
      hash = (53 * hash) + getAskSize2();
      hash = (37 * hash) + ASKSIZE3_FIELD_NUMBER;
      hash = (53 * hash) + getAskSize3();
      hash = (37 * hash) + ASKSIZE4_FIELD_NUMBER;
      hash = (53 * hash) + getAskSize4();
      hash = (37 * hash) + BIDSIZE0_FIELD_NUMBER;
      hash = (53 * hash) + getBidSize0();
      hash = (37 * hash) + BIDSIZE1_FIELD_NUMBER;
      hash = (53 * hash) + getBidSize1();
      hash = (37 * hash) + BIDSIZE2_FIELD_NUMBER;
      hash = (53 * hash) + getBidSize2();
      hash = (37 * hash) + BIDSIZE3_FIELD_NUMBER;
      hash = (53 * hash) + getBidSize3();
      hash = (37 * hash) + BIDSIZE4_FIELD_NUMBER;
      hash = (53 * hash) + getBidSize4();
      hash = (37 * hash) + RECORDID_FIELD_NUMBER;
      hash = (53 * hash) + getRecordId().hashCode();
      hash = (37 * hash) + EXCHANGE_FIELD_NUMBER;
      hash = (53 * hash) + getExchange().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.solutionarchitects.MarketData.MarketDataMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.solutionarchitects.MarketData.MarketDataMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.solutionarchitects.MarketData.MarketDataMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.solutionarchitects.MarketData.MarketDataMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.solutionarchitects.MarketData.MarketDataMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.solutionarchitects.MarketData.MarketDataMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.solutionarchitects.MarketData.MarketDataMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.solutionarchitects.MarketData.MarketDataMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.solutionarchitects.MarketData.MarketDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.solutionarchitects.MarketData.MarketDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.solutionarchitects.MarketData.MarketDataMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.solutionarchitects.MarketDataMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.solutionarchitects.MarketDataMessage)
        com.solutionarchitects.MarketData.MarketDataMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.solutionarchitects.MarketData.internal_static_com_solutionarchitects_MarketDataMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.solutionarchitects.MarketData.internal_static_com_solutionarchitects_MarketDataMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.solutionarchitects.MarketData.MarketDataMessage.class, com.solutionarchitects.MarketData.MarketDataMessage.Builder.class);
      }

      // Construct using com.solutionarchitects.MarketData.MarketDataMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPriceLevelsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (priceLevelsBuilder_ == null) {
          priceLevels_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          priceLevelsBuilder_.clear();
        }
        ask0_ = 0;

        ask1_ = 0;

        ask2_ = 0;

        ask3_ = 0;

        ask4_ = 0;

        bid0_ = 0;

        bid1_ = 0;

        bid2_ = 0;

        bid3_ = 0;

        bid4_ = 0;

        askSize0_ = 0;

        askSize1_ = 0;

        askSize2_ = 0;

        askSize3_ = 0;

        askSize4_ = 0;

        bidSize0_ = 0;

        bidSize1_ = 0;

        bidSize2_ = 0;

        bidSize3_ = 0;

        bidSize4_ = 0;

        recordId_ = "";

        exchange_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.solutionarchitects.MarketData.internal_static_com_solutionarchitects_MarketDataMessage_descriptor;
      }

      public com.solutionarchitects.MarketData.MarketDataMessage getDefaultInstanceForType() {
        return com.solutionarchitects.MarketData.MarketDataMessage.getDefaultInstance();
      }

      public com.solutionarchitects.MarketData.MarketDataMessage build() {
        com.solutionarchitects.MarketData.MarketDataMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.solutionarchitects.MarketData.MarketDataMessage buildPartial() {
        com.solutionarchitects.MarketData.MarketDataMessage result = new com.solutionarchitects.MarketData.MarketDataMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (priceLevelsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            priceLevels_ = java.util.Collections.unmodifiableList(priceLevels_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.priceLevels_ = priceLevels_;
        } else {
          result.priceLevels_ = priceLevelsBuilder_.build();
        }
        result.ask0_ = ask0_;
        result.ask1_ = ask1_;
        result.ask2_ = ask2_;
        result.ask3_ = ask3_;
        result.ask4_ = ask4_;
        result.bid0_ = bid0_;
        result.bid1_ = bid1_;
        result.bid2_ = bid2_;
        result.bid3_ = bid3_;
        result.bid4_ = bid4_;
        result.askSize0_ = askSize0_;
        result.askSize1_ = askSize1_;
        result.askSize2_ = askSize2_;
        result.askSize3_ = askSize3_;
        result.askSize4_ = askSize4_;
        result.bidSize0_ = bidSize0_;
        result.bidSize1_ = bidSize1_;
        result.bidSize2_ = bidSize2_;
        result.bidSize3_ = bidSize3_;
        result.bidSize4_ = bidSize4_;
        result.recordId_ = recordId_;
        result.exchange_ = exchange_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.solutionarchitects.MarketData.MarketDataMessage) {
          return mergeFrom((com.solutionarchitects.MarketData.MarketDataMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.solutionarchitects.MarketData.MarketDataMessage other) {
        if (other == com.solutionarchitects.MarketData.MarketDataMessage.getDefaultInstance()) return this;
        if (priceLevelsBuilder_ == null) {
          if (!other.priceLevels_.isEmpty()) {
            if (priceLevels_.isEmpty()) {
              priceLevels_ = other.priceLevels_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePriceLevelsIsMutable();
              priceLevels_.addAll(other.priceLevels_);
            }
            onChanged();
          }
        } else {
          if (!other.priceLevels_.isEmpty()) {
            if (priceLevelsBuilder_.isEmpty()) {
              priceLevelsBuilder_.dispose();
              priceLevelsBuilder_ = null;
              priceLevels_ = other.priceLevels_;
              bitField0_ = (bitField0_ & ~0x00000001);
              priceLevelsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPriceLevelsFieldBuilder() : null;
            } else {
              priceLevelsBuilder_.addAllMessages(other.priceLevels_);
            }
          }
        }
        if (other.getAsk0() != 0) {
          setAsk0(other.getAsk0());
        }
        if (other.getAsk1() != 0) {
          setAsk1(other.getAsk1());
        }
        if (other.getAsk2() != 0) {
          setAsk2(other.getAsk2());
        }
        if (other.getAsk3() != 0) {
          setAsk3(other.getAsk3());
        }
        if (other.getAsk4() != 0) {
          setAsk4(other.getAsk4());
        }
        if (other.getBid0() != 0) {
          setBid0(other.getBid0());
        }
        if (other.getBid1() != 0) {
          setBid1(other.getBid1());
        }
        if (other.getBid2() != 0) {
          setBid2(other.getBid2());
        }
        if (other.getBid3() != 0) {
          setBid3(other.getBid3());
        }
        if (other.getBid4() != 0) {
          setBid4(other.getBid4());
        }
        if (other.getAskSize0() != 0) {
          setAskSize0(other.getAskSize0());
        }
        if (other.getAskSize1() != 0) {
          setAskSize1(other.getAskSize1());
        }
        if (other.getAskSize2() != 0) {
          setAskSize2(other.getAskSize2());
        }
        if (other.getAskSize3() != 0) {
          setAskSize3(other.getAskSize3());
        }
        if (other.getAskSize4() != 0) {
          setAskSize4(other.getAskSize4());
        }
        if (other.getBidSize0() != 0) {
          setBidSize0(other.getBidSize0());
        }
        if (other.getBidSize1() != 0) {
          setBidSize1(other.getBidSize1());
        }
        if (other.getBidSize2() != 0) {
          setBidSize2(other.getBidSize2());
        }
        if (other.getBidSize3() != 0) {
          setBidSize3(other.getBidSize3());
        }
        if (other.getBidSize4() != 0) {
          setBidSize4(other.getBidSize4());
        }
        if (!other.getRecordId().isEmpty()) {
          recordId_ = other.recordId_;
          onChanged();
        }
        if (!other.getExchange().isEmpty()) {
          exchange_ = other.exchange_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.solutionarchitects.MarketData.MarketDataMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.solutionarchitects.MarketData.MarketDataMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.solutionarchitects.MarketData.Level> priceLevels_ =
        java.util.Collections.emptyList();
      private void ensurePriceLevelsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          priceLevels_ = new java.util.ArrayList<com.solutionarchitects.MarketData.Level>(priceLevels_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.solutionarchitects.MarketData.Level, com.solutionarchitects.MarketData.Level.Builder, com.solutionarchitects.MarketData.LevelOrBuilder> priceLevelsBuilder_;

      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public java.util.List<com.solutionarchitects.MarketData.Level> getPriceLevelsList() {
        if (priceLevelsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(priceLevels_);
        } else {
          return priceLevelsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public int getPriceLevelsCount() {
        if (priceLevelsBuilder_ == null) {
          return priceLevels_.size();
        } else {
          return priceLevelsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public com.solutionarchitects.MarketData.Level getPriceLevels(int index) {
        if (priceLevelsBuilder_ == null) {
          return priceLevels_.get(index);
        } else {
          return priceLevelsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public Builder setPriceLevels(
          int index, com.solutionarchitects.MarketData.Level value) {
        if (priceLevelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePriceLevelsIsMutable();
          priceLevels_.set(index, value);
          onChanged();
        } else {
          priceLevelsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public Builder setPriceLevels(
          int index, com.solutionarchitects.MarketData.Level.Builder builderForValue) {
        if (priceLevelsBuilder_ == null) {
          ensurePriceLevelsIsMutable();
          priceLevels_.set(index, builderForValue.build());
          onChanged();
        } else {
          priceLevelsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public Builder addPriceLevels(com.solutionarchitects.MarketData.Level value) {
        if (priceLevelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePriceLevelsIsMutable();
          priceLevels_.add(value);
          onChanged();
        } else {
          priceLevelsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public Builder addPriceLevels(
          int index, com.solutionarchitects.MarketData.Level value) {
        if (priceLevelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePriceLevelsIsMutable();
          priceLevels_.add(index, value);
          onChanged();
        } else {
          priceLevelsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public Builder addPriceLevels(
          com.solutionarchitects.MarketData.Level.Builder builderForValue) {
        if (priceLevelsBuilder_ == null) {
          ensurePriceLevelsIsMutable();
          priceLevels_.add(builderForValue.build());
          onChanged();
        } else {
          priceLevelsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public Builder addPriceLevels(
          int index, com.solutionarchitects.MarketData.Level.Builder builderForValue) {
        if (priceLevelsBuilder_ == null) {
          ensurePriceLevelsIsMutable();
          priceLevels_.add(index, builderForValue.build());
          onChanged();
        } else {
          priceLevelsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public Builder addAllPriceLevels(
          java.lang.Iterable<? extends com.solutionarchitects.MarketData.Level> values) {
        if (priceLevelsBuilder_ == null) {
          ensurePriceLevelsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, priceLevels_);
          onChanged();
        } else {
          priceLevelsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public Builder clearPriceLevels() {
        if (priceLevelsBuilder_ == null) {
          priceLevels_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          priceLevelsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public Builder removePriceLevels(int index) {
        if (priceLevelsBuilder_ == null) {
          ensurePriceLevelsIsMutable();
          priceLevels_.remove(index);
          onChanged();
        } else {
          priceLevelsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public com.solutionarchitects.MarketData.Level.Builder getPriceLevelsBuilder(
          int index) {
        return getPriceLevelsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public com.solutionarchitects.MarketData.LevelOrBuilder getPriceLevelsOrBuilder(
          int index) {
        if (priceLevelsBuilder_ == null) {
          return priceLevels_.get(index);  } else {
          return priceLevelsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public java.util.List<? extends com.solutionarchitects.MarketData.LevelOrBuilder> 
           getPriceLevelsOrBuilderList() {
        if (priceLevelsBuilder_ != null) {
          return priceLevelsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(priceLevels_);
        }
      }
      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public com.solutionarchitects.MarketData.Level.Builder addPriceLevelsBuilder() {
        return getPriceLevelsFieldBuilder().addBuilder(
            com.solutionarchitects.MarketData.Level.getDefaultInstance());
      }
      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public com.solutionarchitects.MarketData.Level.Builder addPriceLevelsBuilder(
          int index) {
        return getPriceLevelsFieldBuilder().addBuilder(
            index, com.solutionarchitects.MarketData.Level.getDefaultInstance());
      }
      /**
       * <code>repeated .com.solutionarchitects.Level PriceLevels = 1;</code>
       */
      public java.util.List<com.solutionarchitects.MarketData.Level.Builder> 
           getPriceLevelsBuilderList() {
        return getPriceLevelsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.solutionarchitects.MarketData.Level, com.solutionarchitects.MarketData.Level.Builder, com.solutionarchitects.MarketData.LevelOrBuilder> 
          getPriceLevelsFieldBuilder() {
        if (priceLevelsBuilder_ == null) {
          priceLevelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.solutionarchitects.MarketData.Level, com.solutionarchitects.MarketData.Level.Builder, com.solutionarchitects.MarketData.LevelOrBuilder>(
                  priceLevels_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          priceLevels_ = null;
        }
        return priceLevelsBuilder_;
      }

      private int ask0_ ;
      /**
       * <code>optional int32 ask0 = 2;</code>
       */
      public int getAsk0() {
        return ask0_;
      }
      /**
       * <code>optional int32 ask0 = 2;</code>
       */
      public Builder setAsk0(int value) {
        
        ask0_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ask0 = 2;</code>
       */
      public Builder clearAsk0() {
        
        ask0_ = 0;
        onChanged();
        return this;
      }

      private int ask1_ ;
      /**
       * <code>optional int32 ask1 = 3;</code>
       */
      public int getAsk1() {
        return ask1_;
      }
      /**
       * <code>optional int32 ask1 = 3;</code>
       */
      public Builder setAsk1(int value) {
        
        ask1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ask1 = 3;</code>
       */
      public Builder clearAsk1() {
        
        ask1_ = 0;
        onChanged();
        return this;
      }

      private int ask2_ ;
      /**
       * <code>optional int32 ask2 = 4;</code>
       */
      public int getAsk2() {
        return ask2_;
      }
      /**
       * <code>optional int32 ask2 = 4;</code>
       */
      public Builder setAsk2(int value) {
        
        ask2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ask2 = 4;</code>
       */
      public Builder clearAsk2() {
        
        ask2_ = 0;
        onChanged();
        return this;
      }

      private int ask3_ ;
      /**
       * <code>optional int32 ask3 = 5;</code>
       */
      public int getAsk3() {
        return ask3_;
      }
      /**
       * <code>optional int32 ask3 = 5;</code>
       */
      public Builder setAsk3(int value) {
        
        ask3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ask3 = 5;</code>
       */
      public Builder clearAsk3() {
        
        ask3_ = 0;
        onChanged();
        return this;
      }

      private int ask4_ ;
      /**
       * <code>optional int32 ask4 = 6;</code>
       */
      public int getAsk4() {
        return ask4_;
      }
      /**
       * <code>optional int32 ask4 = 6;</code>
       */
      public Builder setAsk4(int value) {
        
        ask4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ask4 = 6;</code>
       */
      public Builder clearAsk4() {
        
        ask4_ = 0;
        onChanged();
        return this;
      }

      private int bid0_ ;
      /**
       * <code>optional int32 bid0 = 7;</code>
       */
      public int getBid0() {
        return bid0_;
      }
      /**
       * <code>optional int32 bid0 = 7;</code>
       */
      public Builder setBid0(int value) {
        
        bid0_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bid0 = 7;</code>
       */
      public Builder clearBid0() {
        
        bid0_ = 0;
        onChanged();
        return this;
      }

      private int bid1_ ;
      /**
       * <code>optional int32 bid1 = 8;</code>
       */
      public int getBid1() {
        return bid1_;
      }
      /**
       * <code>optional int32 bid1 = 8;</code>
       */
      public Builder setBid1(int value) {
        
        bid1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bid1 = 8;</code>
       */
      public Builder clearBid1() {
        
        bid1_ = 0;
        onChanged();
        return this;
      }

      private int bid2_ ;
      /**
       * <code>optional int32 bid2 = 9;</code>
       */
      public int getBid2() {
        return bid2_;
      }
      /**
       * <code>optional int32 bid2 = 9;</code>
       */
      public Builder setBid2(int value) {
        
        bid2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bid2 = 9;</code>
       */
      public Builder clearBid2() {
        
        bid2_ = 0;
        onChanged();
        return this;
      }

      private int bid3_ ;
      /**
       * <code>optional int32 bid3 = 11;</code>
       */
      public int getBid3() {
        return bid3_;
      }
      /**
       * <code>optional int32 bid3 = 11;</code>
       */
      public Builder setBid3(int value) {
        
        bid3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bid3 = 11;</code>
       */
      public Builder clearBid3() {
        
        bid3_ = 0;
        onChanged();
        return this;
      }

      private int bid4_ ;
      /**
       * <code>optional int32 bid4 = 12;</code>
       */
      public int getBid4() {
        return bid4_;
      }
      /**
       * <code>optional int32 bid4 = 12;</code>
       */
      public Builder setBid4(int value) {
        
        bid4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bid4 = 12;</code>
       */
      public Builder clearBid4() {
        
        bid4_ = 0;
        onChanged();
        return this;
      }

      private int askSize0_ ;
      /**
       * <code>optional int32 askSize0 = 13;</code>
       */
      public int getAskSize0() {
        return askSize0_;
      }
      /**
       * <code>optional int32 askSize0 = 13;</code>
       */
      public Builder setAskSize0(int value) {
        
        askSize0_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 askSize0 = 13;</code>
       */
      public Builder clearAskSize0() {
        
        askSize0_ = 0;
        onChanged();
        return this;
      }

      private int askSize1_ ;
      /**
       * <code>optional int32 askSize1 = 14;</code>
       */
      public int getAskSize1() {
        return askSize1_;
      }
      /**
       * <code>optional int32 askSize1 = 14;</code>
       */
      public Builder setAskSize1(int value) {
        
        askSize1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 askSize1 = 14;</code>
       */
      public Builder clearAskSize1() {
        
        askSize1_ = 0;
        onChanged();
        return this;
      }

      private int askSize2_ ;
      /**
       * <code>optional int32 askSize2 = 15;</code>
       */
      public int getAskSize2() {
        return askSize2_;
      }
      /**
       * <code>optional int32 askSize2 = 15;</code>
       */
      public Builder setAskSize2(int value) {
        
        askSize2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 askSize2 = 15;</code>
       */
      public Builder clearAskSize2() {
        
        askSize2_ = 0;
        onChanged();
        return this;
      }

      private int askSize3_ ;
      /**
       * <code>optional int32 askSize3 = 16;</code>
       */
      public int getAskSize3() {
        return askSize3_;
      }
      /**
       * <code>optional int32 askSize3 = 16;</code>
       */
      public Builder setAskSize3(int value) {
        
        askSize3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 askSize3 = 16;</code>
       */
      public Builder clearAskSize3() {
        
        askSize3_ = 0;
        onChanged();
        return this;
      }

      private int askSize4_ ;
      /**
       * <code>optional int32 askSize4 = 17;</code>
       */
      public int getAskSize4() {
        return askSize4_;
      }
      /**
       * <code>optional int32 askSize4 = 17;</code>
       */
      public Builder setAskSize4(int value) {
        
        askSize4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 askSize4 = 17;</code>
       */
      public Builder clearAskSize4() {
        
        askSize4_ = 0;
        onChanged();
        return this;
      }

      private int bidSize0_ ;
      /**
       * <code>optional int32 bidSize0 = 18;</code>
       */
      public int getBidSize0() {
        return bidSize0_;
      }
      /**
       * <code>optional int32 bidSize0 = 18;</code>
       */
      public Builder setBidSize0(int value) {
        
        bidSize0_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bidSize0 = 18;</code>
       */
      public Builder clearBidSize0() {
        
        bidSize0_ = 0;
        onChanged();
        return this;
      }

      private int bidSize1_ ;
      /**
       * <code>optional int32 bidSize1 = 19;</code>
       */
      public int getBidSize1() {
        return bidSize1_;
      }
      /**
       * <code>optional int32 bidSize1 = 19;</code>
       */
      public Builder setBidSize1(int value) {
        
        bidSize1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bidSize1 = 19;</code>
       */
      public Builder clearBidSize1() {
        
        bidSize1_ = 0;
        onChanged();
        return this;
      }

      private int bidSize2_ ;
      /**
       * <code>optional int32 bidSize2 = 20;</code>
       */
      public int getBidSize2() {
        return bidSize2_;
      }
      /**
       * <code>optional int32 bidSize2 = 20;</code>
       */
      public Builder setBidSize2(int value) {
        
        bidSize2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bidSize2 = 20;</code>
       */
      public Builder clearBidSize2() {
        
        bidSize2_ = 0;
        onChanged();
        return this;
      }

      private int bidSize3_ ;
      /**
       * <code>optional int32 bidSize3 = 21;</code>
       */
      public int getBidSize3() {
        return bidSize3_;
      }
      /**
       * <code>optional int32 bidSize3 = 21;</code>
       */
      public Builder setBidSize3(int value) {
        
        bidSize3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bidSize3 = 21;</code>
       */
      public Builder clearBidSize3() {
        
        bidSize3_ = 0;
        onChanged();
        return this;
      }

      private int bidSize4_ ;
      /**
       * <code>optional int32 bidSize4 = 22;</code>
       */
      public int getBidSize4() {
        return bidSize4_;
      }
      /**
       * <code>optional int32 bidSize4 = 22;</code>
       */
      public Builder setBidSize4(int value) {
        
        bidSize4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bidSize4 = 22;</code>
       */
      public Builder clearBidSize4() {
        
        bidSize4_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object recordId_ = "";
      /**
       * <code>optional string recordId = 23;</code>
       */
      public java.lang.String getRecordId() {
        java.lang.Object ref = recordId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          recordId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string recordId = 23;</code>
       */
      public com.google.protobuf.ByteString
          getRecordIdBytes() {
        java.lang.Object ref = recordId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          recordId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string recordId = 23;</code>
       */
      public Builder setRecordId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        recordId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string recordId = 23;</code>
       */
      public Builder clearRecordId() {
        
        recordId_ = getDefaultInstance().getRecordId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string recordId = 23;</code>
       */
      public Builder setRecordIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        recordId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object exchange_ = "";
      /**
       * <code>optional string exchange = 24;</code>
       */
      public java.lang.String getExchange() {
        java.lang.Object ref = exchange_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          exchange_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string exchange = 24;</code>
       */
      public com.google.protobuf.ByteString
          getExchangeBytes() {
        java.lang.Object ref = exchange_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exchange_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string exchange = 24;</code>
       */
      public Builder setExchange(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        exchange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string exchange = 24;</code>
       */
      public Builder clearExchange() {
        
        exchange_ = getDefaultInstance().getExchange();
        onChanged();
        return this;
      }
      /**
       * <code>optional string exchange = 24;</code>
       */
      public Builder setExchangeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        exchange_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.solutionarchitects.MarketDataMessage)
    }

    // @@protoc_insertion_point(class_scope:com.solutionarchitects.MarketDataMessage)
    private static final com.solutionarchitects.MarketData.MarketDataMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.solutionarchitects.MarketData.MarketDataMessage();
    }

    public static com.solutionarchitects.MarketData.MarketDataMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MarketDataMessage>
        PARSER = new com.google.protobuf.AbstractParser<MarketDataMessage>() {
      public MarketDataMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MarketDataMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MarketDataMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MarketDataMessage> getParserForType() {
      return PARSER;
    }

    public com.solutionarchitects.MarketData.MarketDataMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_solutionarchitects_Level_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_solutionarchitects_Level_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_solutionarchitects_MarketDataMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_solutionarchitects_MarketDataMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020MarketData.proto\022\026com.solutionarchitec" +
      "ts\"8\n\005Level\022\r\n\005price\030\001 \001(\001\022\017\n\007askSize\030\002 " +
      "\001(\005\022\017\n\007bidSize\030\003 \001(\005\"\253\003\n\021MarketDataMessa" +
      "ge\0222\n\013PriceLevels\030\001 \003(\0132\035.com.solutionar" +
      "chitects.Level\022\014\n\004ask0\030\002 \001(\005\022\014\n\004ask1\030\003 \001" +
      "(\005\022\014\n\004ask2\030\004 \001(\005\022\014\n\004ask3\030\005 \001(\005\022\014\n\004ask4\030\006" +
      " \001(\005\022\014\n\004bid0\030\007 \001(\005\022\014\n\004bid1\030\010 \001(\005\022\014\n\004bid2" +
      "\030\t \001(\005\022\014\n\004bid3\030\013 \001(\005\022\014\n\004bid4\030\014 \001(\005\022\020\n\010as" +
      "kSize0\030\r \001(\005\022\020\n\010askSize1\030\016 \001(\005\022\020\n\010askSiz" +
      "e2\030\017 \001(\005\022\020\n\010askSize3\030\020 \001(\005\022\020\n\010askSize4\030\021",
      " \001(\005\022\020\n\010bidSize0\030\022 \001(\005\022\020\n\010bidSize1\030\023 \001(\005" +
      "\022\020\n\010bidSize2\030\024 \001(\005\022\020\n\010bidSize3\030\025 \001(\005\022\020\n\010" +
      "bidSize4\030\026 \001(\005\022\020\n\010recordId\030\027 \001(\t\022\020\n\010exch" +
      "ange\030\030 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_solutionarchitects_Level_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_solutionarchitects_Level_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_solutionarchitects_Level_descriptor,
        new java.lang.String[] { "Price", "AskSize", "BidSize", });
    internal_static_com_solutionarchitects_MarketDataMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_solutionarchitects_MarketDataMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_solutionarchitects_MarketDataMessage_descriptor,
        new java.lang.String[] { "PriceLevels", "Ask0", "Ask1", "Ask2", "Ask3", "Ask4", "Bid0", "Bid1", "Bid2", "Bid3", "Bid4", "AskSize0", "AskSize1", "AskSize2", "AskSize3", "AskSize4", "BidSize0", "BidSize1", "BidSize2", "BidSize3", "BidSize4", "RecordId", "Exchange", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
